// <auto-generated />
// Generated by Scripts/Generate-Component-Proxies.ps1 from ComponentProxies.json.
#nullable enable

namespace TomCat;

internal static class GeneratedRegisteredComponentProxies
{
    private readonly record struct Entry(
        ulong TypeId, Func<Entity, IEntityComponent> Factory);

    private static readonly IReadOnlyDictionary<Type, Entry> s_entries =
        new Dictionary<Type, Entry>
        {
            [typeof(HealthComponent)] = new(0x8d0df196efd946a1UL,
                static entity => new HealthComponent(entity)),
            [typeof(Transform)] = new(0x9f00000000000004UL,
                static entity => new Transform(entity)),
            [typeof(Camera)] = new(0x9f00000000000005UL,
                static entity => new Camera(entity)),
            [typeof(SpriteRenderer)] = new(0x9f00000000000006UL,
                static entity => new SpriteRenderer(entity)),
            [typeof(SpriteAnimator)] = new(0x9f00000000000007UL,
                static entity => new SpriteAnimator(entity)),
            [typeof(AudioSource)] = new(0x9f0000000000000aUL,
                static entity => new AudioSource(entity)),
            [typeof(AudioListener)] = new(0x9f0000000000000bUL,
                static entity => new AudioListener(entity)),
            [typeof(Rigidbody2D)] = new(0x9f0000000000000cUL,
                static entity => new Rigidbody2D(entity)),
            [typeof(BoxCollider2D)] = new(0x9f0000000000000dUL,
                static entity => new BoxCollider2D(entity)),
            [typeof(CircleCollider2D)] = new(0x9f0000000000000eUL,
                static entity => new CircleCollider2D(entity)),
            [typeof(DistanceJoint2D)] = new(0x9f0000000000000fUL,
                static entity => new DistanceJoint2D(entity)),
            [typeof(TextRenderer)] = new(0x9f01000000000001UL,
                static entity => new TextRenderer(entity)),
            [typeof(Canvas)] = new(0x9f01000000000002UL,
                static entity => new Canvas(entity)),
            [typeof(RectTransform)] = new(0x9f01000000000003UL,
                static entity => new RectTransform(entity)),
            [typeof(UIImage)] = new(0x9f01000000000004UL,
                static entity => new UIImage(entity)),
            [typeof(UIText)] = new(0x9f01000000000005UL,
                static entity => new UIText(entity)),
            [typeof(UIButton)] = new(0x9f01000000000006UL,
                static entity => new UIButton(entity)),
            [typeof(UIEventSystem)] = new(0x9f01000000000007UL,
                static entity => new UIEventSystem(entity)),
            [typeof(UILayoutGroup)] = new(0x9f01000000000008UL,
                static entity => new UILayoutGroup(entity)),
        };

    internal static bool TryCreate<T>(Entity entity, out T component)
        where T : class, IEntityComponent
    {
        if (s_entries.TryGetValue(typeof(T), out Entry entry))
        {
            component = (T)entry.Factory(entity);
            return true;
        }
        component = null!;
        return false;
    }

    internal static bool TryGetTypeId<T>(out ulong typeId)
        where T : class, IEntityComponent
    {
        if (s_entries.TryGetValue(typeof(T), out Entry entry))
        {
            typeId = entry.TypeId;
            return true;
        }
        typeId = 0;
        return false;
    }
}

[RegisteredComponent(0x9f00000000000005UL)]
public sealed partial class Camera : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000005UL;

    internal Camera(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Primary
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x000000000000012cUL, "Camera.Primary");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x000000000000012cUL, value, "Camera.Primary");
    }

    public bool FixedAspectRatio
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x000000000000012dUL, "Camera.FixedAspectRatio");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x000000000000012dUL, value, "Camera.FixedAspectRatio");
    }

    public Color BackgroundColor
    {
        get => NativeBridge.GetRegisteredColor(Entity, RegisteredTypeId, 0x000000000000012eUL, "Camera.BackgroundColor");
        set => NativeBridge.SetRegisteredColor(Entity, RegisteredTypeId,
            0x000000000000012eUL, value, "Camera.BackgroundColor");
    }

    public CameraProjectionType ProjectionType
    {
        get => (CameraProjectionType)NativeBridge.GetRegisteredInt32(Entity, RegisteredTypeId, 0x000000000000012fUL, "Camera.ProjectionType");
        set => NativeBridge.SetRegisteredInt32(Entity, RegisteredTypeId,
            0x000000000000012fUL, (int)value, "Camera.ProjectionType");
    }

    public float OrthographicSize
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000130UL, "Camera.OrthographicSize");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000130UL, value, "Camera.OrthographicSize");
    }

    public float OrthographicNearClip
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000131UL, "Camera.OrthographicNearClip");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000131UL, value, "Camera.OrthographicNearClip");
    }

    public float OrthographicFarClip
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000132UL, "Camera.OrthographicFarClip");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000132UL, value, "Camera.OrthographicFarClip");
    }

    public float PerspectiveVerticalFov
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000133UL, "Camera.PerspectiveVerticalFov");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000133UL, value, "Camera.PerspectiveVerticalFov");
    }

    public float PerspectiveNearClip
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000134UL, "Camera.PerspectiveNearClip");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000134UL, value, "Camera.PerspectiveNearClip");
    }

    public float PerspectiveFarClip
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000135UL, "Camera.PerspectiveFarClip");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000135UL, value, "Camera.PerspectiveFarClip");
    }
}

[RegisteredComponent(0x9f00000000000006UL)]
public sealed partial class SpriteRenderer : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000006UL;

    internal SpriteRenderer(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x00000000000000c8UL, "SpriteRenderer.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x00000000000000c8UL, value, "SpriteRenderer.Enabled");
    }

    public Color Color
    {
        get => NativeBridge.GetRegisteredColor(Entity, RegisteredTypeId, 0x00000000000000c9UL, "SpriteRenderer.Color");
        set => NativeBridge.SetRegisteredColor(Entity, RegisteredTypeId,
            0x00000000000000c9UL, value, "SpriteRenderer.Color");
    }

    public AssetRef<Texture2DAsset> Sprite
    {
        get => new(NativeBridge.GetRegisteredUInt64(Entity, RegisteredTypeId, 0x00000000000000caUL, "SpriteRenderer.Sprite"));
        set => NativeBridge.SetRegisteredUInt64(Entity, RegisteredTypeId,
            0x00000000000000caUL, value.Handle, "SpriteRenderer.Sprite");
    }

    public float TilingFactor
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000000cbUL, "SpriteRenderer.TilingFactor");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000000cbUL, value, "SpriteRenderer.TilingFactor");
    }

    public int SortingLayer
    {
        get => NativeBridge.GetRegisteredInt32(Entity, RegisteredTypeId, 0x00000000000000ccUL, "SpriteRenderer.SortingLayer");
        set => NativeBridge.SetRegisteredInt32(Entity, RegisteredTypeId,
            0x00000000000000ccUL, value, "SpriteRenderer.SortingLayer");
    }

    public int OrderInLayer
    {
        get => NativeBridge.GetRegisteredInt32(Entity, RegisteredTypeId, 0x00000000000000cdUL, "SpriteRenderer.OrderInLayer");
        set => NativeBridge.SetRegisteredInt32(Entity, RegisteredTypeId,
            0x00000000000000cdUL, value, "SpriteRenderer.OrderInLayer");
    }
}

[RegisteredComponent(0x9f00000000000007UL)]
public sealed partial class SpriteAnimator : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000007UL;

    internal SpriteAnimator(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x00000000000002bcUL, "SpriteAnimator.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x00000000000002bcUL, value, "SpriteAnimator.Enabled");
    }

    public float Speed
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000002bdUL, "SpriteAnimator.Speed");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000002bdUL, value, "SpriteAnimator.Speed");
    }

    public bool PlayOnStart
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x00000000000002c0UL, "SpriteAnimator.PlayOnStart");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x00000000000002c0UL, value, "SpriteAnimator.PlayOnStart");
    }
}

[RegisteredComponent(0x9f0000000000000aUL)]
public sealed partial class AudioSource : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000aUL;

    internal AudioSource(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000384UL, "AudioSource.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000384UL, value, "AudioSource.Enabled");
    }

    public AssetRef<AudioAsset> Clip
    {
        get => new(NativeBridge.GetRegisteredUInt64(Entity, RegisteredTypeId, 0x0000000000000385UL, "AudioSource.Clip"));
        set => NativeBridge.SetRegisteredUInt64(Entity, RegisteredTypeId,
            0x0000000000000385UL, value.Handle, "AudioSource.Clip");
    }

    public bool PlayOnStart
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000386UL, "AudioSource.PlayOnStart");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000386UL, value, "AudioSource.PlayOnStart");
    }

    public bool Loop
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000387UL, "AudioSource.Loop");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000387UL, value, "AudioSource.Loop");
    }

    public bool Streaming
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000388UL, "AudioSource.Streaming");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000388UL, value, "AudioSource.Streaming");
    }

    public float Volume
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000389UL, "AudioSource.Volume");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000389UL, value, "AudioSource.Volume");
    }

    public float Pitch
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000038aUL, "AudioSource.Pitch");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000038aUL, value, "AudioSource.Pitch");
    }

    public float SpatialBlend
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000038bUL, "AudioSource.SpatialBlend");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000038bUL, value, "AudioSource.SpatialBlend");
    }

    public float MinDistance
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000038cUL, "AudioSource.MinDistance");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000038cUL, value, "AudioSource.MinDistance");
    }

    public float MaxDistance
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000038dUL, "AudioSource.MaxDistance");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000038dUL, value, "AudioSource.MaxDistance");
    }

    public AudioMixerGroup MixerGroup
    {
        get => (AudioMixerGroup)NativeBridge.GetRegisteredUInt32(Entity, RegisteredTypeId, 0x000000000000038eUL, "AudioSource.MixerGroup");
        set => NativeBridge.SetRegisteredUInt32(Entity, RegisteredTypeId,
            0x000000000000038eUL, (uint)value, "AudioSource.MixerGroup");
    }
}

[RegisteredComponent(0x9f0000000000000bUL)]
public sealed partial class AudioListener : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000bUL;

    internal AudioListener(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000398UL, "AudioListener.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000398UL, value, "AudioListener.Enabled");
    }

    public bool Primary
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000399UL, "AudioListener.Primary");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000399UL, value, "AudioListener.Primary");
    }
}

[RegisteredComponent(0x9f0000000000000cUL)]
public sealed partial class Rigidbody2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000cUL;

    internal Rigidbody2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000064UL, "Rigidbody2D.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000064UL, value, "Rigidbody2D.Enabled");
    }

    public RigidbodyBodyType BodyType
    {
        get => (RigidbodyBodyType)NativeBridge.GetRegisteredInt32(Entity, RegisteredTypeId, 0x0000000000000065UL, "Rigidbody2D.BodyType");
        set => NativeBridge.SetRegisteredInt32(Entity, RegisteredTypeId,
            0x0000000000000065UL, (int)value, "Rigidbody2D.BodyType");
    }

    public bool FixedRotation
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000066UL, "Rigidbody2D.FixedRotation");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000066UL, value, "Rigidbody2D.FixedRotation");
    }
}

[RegisteredComponent(0x9f0000000000000dUL)]
public sealed partial class BoxCollider2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000dUL;

    internal BoxCollider2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000190UL, "BoxCollider2D.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000190UL, value, "BoxCollider2D.Enabled");
    }

    public bool IsTrigger
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000191UL, "BoxCollider2D.IsTrigger");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000191UL, value, "BoxCollider2D.IsTrigger");
    }

    public uint CollisionLayer
    {
        get => NativeBridge.GetRegisteredUInt32(Entity, RegisteredTypeId, 0x0000000000000192UL, "BoxCollider2D.CollisionLayer");
        set => NativeBridge.SetRegisteredUInt32(Entity, RegisteredTypeId,
            0x0000000000000192UL, value, "BoxCollider2D.CollisionLayer");
    }

    public uint CollisionMask
    {
        get => NativeBridge.GetRegisteredUInt32(Entity, RegisteredTypeId, 0x0000000000000193UL, "BoxCollider2D.CollisionMask");
        set => NativeBridge.SetRegisteredUInt32(Entity, RegisteredTypeId,
            0x0000000000000193UL, value, "BoxCollider2D.CollisionMask");
    }

    public Vector2 Offset
    {
        get => NativeBridge.GetRegisteredVector2(Entity, RegisteredTypeId, 0x0000000000000194UL, "BoxCollider2D.Offset");
        set => NativeBridge.SetRegisteredVector2(Entity, RegisteredTypeId,
            0x0000000000000194UL, value, "BoxCollider2D.Offset");
    }

    public Vector2 Size
    {
        get => NativeBridge.GetRegisteredVector2(Entity, RegisteredTypeId, 0x0000000000000195UL, "BoxCollider2D.Size");
        set => NativeBridge.SetRegisteredVector2(Entity, RegisteredTypeId,
            0x0000000000000195UL, value, "BoxCollider2D.Size");
    }

    public float Density
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000196UL, "BoxCollider2D.Density");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000196UL, value, "BoxCollider2D.Density");
    }

    public float Friction
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000197UL, "BoxCollider2D.Friction");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000197UL, value, "BoxCollider2D.Friction");
    }

    public float Restitution
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000198UL, "BoxCollider2D.Restitution");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000198UL, value, "BoxCollider2D.Restitution");
    }

    public float RestitutionThreshold
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x0000000000000199UL, "BoxCollider2D.RestitutionThreshold");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x0000000000000199UL, value, "BoxCollider2D.RestitutionThreshold");
    }
}

[RegisteredComponent(0x9f0000000000000eUL)]
public sealed partial class CircleCollider2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000eUL;

    internal CircleCollider2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x00000000000001f4UL, "CircleCollider2D.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x00000000000001f4UL, value, "CircleCollider2D.Enabled");
    }

    public bool IsTrigger
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x00000000000001f5UL, "CircleCollider2D.IsTrigger");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x00000000000001f5UL, value, "CircleCollider2D.IsTrigger");
    }

    public uint CollisionLayer
    {
        get => NativeBridge.GetRegisteredUInt32(Entity, RegisteredTypeId, 0x00000000000001f6UL, "CircleCollider2D.CollisionLayer");
        set => NativeBridge.SetRegisteredUInt32(Entity, RegisteredTypeId,
            0x00000000000001f6UL, value, "CircleCollider2D.CollisionLayer");
    }

    public uint CollisionMask
    {
        get => NativeBridge.GetRegisteredUInt32(Entity, RegisteredTypeId, 0x00000000000001f7UL, "CircleCollider2D.CollisionMask");
        set => NativeBridge.SetRegisteredUInt32(Entity, RegisteredTypeId,
            0x00000000000001f7UL, value, "CircleCollider2D.CollisionMask");
    }

    public Vector2 Offset
    {
        get => NativeBridge.GetRegisteredVector2(Entity, RegisteredTypeId, 0x00000000000001f8UL, "CircleCollider2D.Offset");
        set => NativeBridge.SetRegisteredVector2(Entity, RegisteredTypeId,
            0x00000000000001f8UL, value, "CircleCollider2D.Offset");
    }

    public float Radius
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000001f9UL, "CircleCollider2D.Radius");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000001f9UL, value, "CircleCollider2D.Radius");
    }

    public float Density
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000001faUL, "CircleCollider2D.Density");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000001faUL, value, "CircleCollider2D.Density");
    }

    public float Friction
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000001fbUL, "CircleCollider2D.Friction");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000001fbUL, value, "CircleCollider2D.Friction");
    }

    public float Restitution
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x00000000000001fcUL, "CircleCollider2D.Restitution");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x00000000000001fcUL, value, "CircleCollider2D.Restitution");
    }
}

[RegisteredComponent(0x9f0000000000000fUL)]
public sealed partial class DistanceJoint2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000fUL;

    internal DistanceJoint2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x0000000000000258UL, "DistanceJoint2D.Enabled");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x0000000000000258UL, value, "DistanceJoint2D.Enabled");
    }

    public Vector2 Anchor
    {
        get => NativeBridge.GetRegisteredVector2(Entity, RegisteredTypeId, 0x000000000000025aUL, "DistanceJoint2D.Anchor");
        set => NativeBridge.SetRegisteredVector2(Entity, RegisteredTypeId,
            0x000000000000025aUL, value, "DistanceJoint2D.Anchor");
    }

    public Vector2 ConnectedAnchor
    {
        get => NativeBridge.GetRegisteredVector2(Entity, RegisteredTypeId, 0x000000000000025bUL, "DistanceJoint2D.ConnectedAnchor");
        set => NativeBridge.SetRegisteredVector2(Entity, RegisteredTypeId,
            0x000000000000025bUL, value, "DistanceJoint2D.ConnectedAnchor");
    }

    public float Distance
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000025cUL, "DistanceJoint2D.Distance");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000025cUL, value, "DistanceJoint2D.Distance");
    }

    public float Frequency
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000025dUL, "DistanceJoint2D.Frequency");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000025dUL, value, "DistanceJoint2D.Frequency");
    }

    public float Damping
    {
        get => NativeBridge.GetRegisteredFloat(Entity, RegisteredTypeId, 0x000000000000025eUL, "DistanceJoint2D.Damping");
        set => NativeBridge.SetRegisteredFloat(Entity, RegisteredTypeId,
            0x000000000000025eUL, value, "DistanceJoint2D.Damping");
    }

    public bool CollideConnected
    {
        get => NativeBridge.GetRegisteredBool(Entity, RegisteredTypeId, 0x000000000000025fUL, "DistanceJoint2D.CollideConnected");
        set => NativeBridge.SetRegisteredBool(Entity, RegisteredTypeId,
            0x000000000000025fUL, value, "DistanceJoint2D.CollideConnected");
    }
}
