// <auto-generated />
// Generated by Scripts/Generate-Component-Proxies.ps1 from ComponentProxies.json.
#nullable enable

namespace TomCat;

internal static class GeneratedRegisteredComponentProxies
{
    private readonly record struct Entry(
        ulong TypeId, Func<Entity, IEntityComponent> Factory);

    private static readonly IReadOnlyDictionary<Type, Entry> s_entries =
        new Dictionary<Type, Entry>
        {
            [typeof(HealthComponent)] = new(0x8d0df196efd946a1UL,
                static entity => new HealthComponent(entity)),
            [typeof(Transform)] = new(0x9f00000000000004UL,
                static entity => new Transform(entity)),
            [typeof(Camera)] = new(0x9f00000000000005UL,
                static entity => new Camera(entity)),
            [typeof(SpriteRenderer)] = new(0x9f00000000000006UL,
                static entity => new SpriteRenderer(entity)),
            [typeof(SpriteAnimator)] = new(0x9f00000000000007UL,
                static entity => new SpriteAnimator(entity)),
            [typeof(AudioSource)] = new(0x9f0000000000000aUL,
                static entity => new AudioSource(entity)),
            [typeof(AudioListener)] = new(0x9f0000000000000bUL,
                static entity => new AudioListener(entity)),
            [typeof(Rigidbody2D)] = new(0x9f0000000000000cUL,
                static entity => new Rigidbody2D(entity)),
            [typeof(BoxCollider2D)] = new(0x9f0000000000000dUL,
                static entity => new BoxCollider2D(entity)),
            [typeof(CircleCollider2D)] = new(0x9f0000000000000eUL,
                static entity => new CircleCollider2D(entity)),
            [typeof(DistanceJoint2D)] = new(0x9f0000000000000fUL,
                static entity => new DistanceJoint2D(entity)),
            [typeof(MeshRenderer)] = new(0x9f00000000000016UL,
                static entity => new MeshRenderer(entity)),
            [typeof(Light3D)] = new(0x9f00000000000017UL,
                static entity => new Light3D(entity)),
            [typeof(Environment3D)] = new(0x9f00000000000018UL,
                static entity => new Environment3D(entity)),
            [typeof(TextRenderer)] = new(0x9f01000000000001UL,
                static entity => new TextRenderer(entity)),
            [typeof(Canvas)] = new(0x9f01000000000002UL,
                static entity => new Canvas(entity)),
            [typeof(RectTransform)] = new(0x9f01000000000003UL,
                static entity => new RectTransform(entity)),
            [typeof(UIImage)] = new(0x9f01000000000004UL,
                static entity => new UIImage(entity)),
            [typeof(UIText)] = new(0x9f01000000000005UL,
                static entity => new UIText(entity)),
            [typeof(UIButton)] = new(0x9f01000000000006UL,
                static entity => new UIButton(entity)),
            [typeof(UIEventSystem)] = new(0x9f01000000000007UL,
                static entity => new UIEventSystem(entity)),
            [typeof(UILayoutGroup)] = new(0x9f01000000000008UL,
                static entity => new UILayoutGroup(entity)),
            [typeof(UISlider)] = new(0x9f01000000000009UL,
                static entity => new UISlider(entity)),
            [typeof(UIScrollView)] = new(0x9f0100000000000aUL,
                static entity => new UIScrollView(entity)),
            [typeof(UIInputField)] = new(0x9f0100000000000bUL,
                static entity => new UIInputField(entity)),
            [typeof(UITheme)] = new(0x9f0100000000000cUL,
                static entity => new UITheme(entity)),
            [typeof(UILocalization)] = new(0x9f0100000000000dUL,
                static entity => new UILocalization(entity)),
            [typeof(UILocalizedText)] = new(0x9f0100000000000eUL,
                static entity => new UILocalizedText(entity)),
        };

    internal static bool TryCreate<T>(Entity entity, out T component)
        where T : class, IEntityComponent
    {
        if (s_entries.TryGetValue(typeof(T), out Entry entry))
        {
            component = (T)entry.Factory(entity);
            return true;
        }
        component = null!;
        return false;
    }

    internal static bool TryGetTypeId<T>(out ulong typeId)
        where T : class, IEntityComponent
    {
        if (s_entries.TryGetValue(typeof(T), out Entry entry))
        {
            typeId = entry.TypeId;
            return true;
        }
        typeId = 0;
        return false;
    }
}

[RegisteredComponent(0x9f00000000000005UL)]
public sealed partial class Camera : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000005UL;

    internal Camera(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Primary
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x000000000000012cUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x000000000000012cUL, value);
    }

    public bool FixedAspectRatio
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x000000000000012dUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x000000000000012dUL, value);
    }

    public Color BackgroundColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x000000000000012eUL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x000000000000012eUL, value);
    }

    public CameraProjectionType ProjectionType
    {
        get => (CameraProjectionType)RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x000000000000012fUL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x000000000000012fUL, (int)value);
    }

    public float OrthographicSize
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000130UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000130UL, value);
    }

    public float OrthographicNearClip
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000131UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000131UL, value);
    }

    public float OrthographicFarClip
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000132UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000132UL, value);
    }

    public float PerspectiveVerticalFov
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000133UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000133UL, value);
    }

    public float PerspectiveNearClip
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000134UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000134UL, value);
    }

    public float PerspectiveFarClip
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000135UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000135UL, value);
    }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000136UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000136UL, value);
    }
}

[RegisteredComponent(0x9f00000000000006UL)]
public sealed partial class SpriteRenderer : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000006UL;

    internal SpriteRenderer(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000000c8UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000000c8UL, value);
    }

    public Color Color
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x00000000000000c9UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x00000000000000c9UL, value);
    }

    public AssetRef<Texture2DAsset> Sprite
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x00000000000000caUL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x00000000000000caUL, value.Handle);
    }

    public float TilingFactor
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000000cbUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000000cbUL, value);
    }

    public int SortingLayer
    {
        get => RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x00000000000000ccUL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x00000000000000ccUL, value);
    }

    public int OrderInLayer
    {
        get => RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x00000000000000cdUL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x00000000000000cdUL, value);
    }
}

[RegisteredComponent(0x9f00000000000007UL)]
public sealed partial class SpriteAnimator : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000007UL;

    internal SpriteAnimator(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000002bcUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000002bcUL, value);
    }

    public float Speed
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000002bdUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000002bdUL, value);
    }

    public bool PlayOnStart
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000002c0UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000002c0UL, value);
    }
}

[RegisteredComponent(0x9f0000000000000aUL)]
public sealed partial class AudioSource : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000aUL;

    internal AudioSource(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000384UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000384UL, value);
    }

    public AssetRef<AudioAsset> Clip
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x0000000000000385UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x0000000000000385UL, value.Handle);
    }

    public bool PlayOnStart
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000386UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000386UL, value);
    }

    public bool Loop
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000387UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000387UL, value);
    }

    public bool Streaming
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000388UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000388UL, value);
    }

    public float Volume
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000389UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000389UL, value);
    }

    public float Pitch
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000038aUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000038aUL, value);
    }

    public float SpatialBlend
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000038bUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000038bUL, value);
    }

    public float MinDistance
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000038cUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000038cUL, value);
    }

    public float MaxDistance
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000038dUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000038dUL, value);
    }

    public AudioMixerGroup MixerGroup
    {
        get => (AudioMixerGroup)RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x000000000000038eUL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x000000000000038eUL, (uint)value);
    }
}

[RegisteredComponent(0x9f0000000000000bUL)]
public sealed partial class AudioListener : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000bUL;

    internal AudioListener(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000398UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000398UL, value);
    }

    public bool Primary
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000399UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000399UL, value);
    }
}

[RegisteredComponent(0x9f0000000000000cUL)]
public sealed partial class Rigidbody2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000cUL;

    internal Rigidbody2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000064UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000064UL, value);
    }

    public RigidbodyBodyType BodyType
    {
        get => (RigidbodyBodyType)RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x0000000000000065UL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x0000000000000065UL, (int)value);
    }

    public bool FixedRotation
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000066UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000066UL, value);
    }
}

[RegisteredComponent(0x9f0000000000000dUL)]
public sealed partial class BoxCollider2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000dUL;

    internal BoxCollider2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000190UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000190UL, value);
    }

    public bool IsTrigger
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000191UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000191UL, value);
    }

    public uint CollisionLayer
    {
        get => RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x0000000000000192UL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x0000000000000192UL, value);
    }

    public uint CollisionMask
    {
        get => RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x0000000000000193UL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x0000000000000193UL, value);
    }

    public Vector2 Offset
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x0000000000000194UL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x0000000000000194UL, value);
    }

    public Vector2 Size
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x0000000000000195UL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x0000000000000195UL, value);
    }

    public float Density
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000196UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000196UL, value);
    }

    public float Friction
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000197UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000197UL, value);
    }

    public float Restitution
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000198UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000198UL, value);
    }

    public float RestitutionThreshold
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000199UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000199UL, value);
    }
}

[RegisteredComponent(0x9f0000000000000eUL)]
public sealed partial class CircleCollider2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000eUL;

    internal CircleCollider2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000001f4UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000001f4UL, value);
    }

    public bool IsTrigger
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000001f5UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000001f5UL, value);
    }

    public uint CollisionLayer
    {
        get => RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x00000000000001f6UL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x00000000000001f6UL, value);
    }

    public uint CollisionMask
    {
        get => RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x00000000000001f7UL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x00000000000001f7UL, value);
    }

    public Vector2 Offset
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x00000000000001f8UL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x00000000000001f8UL, value);
    }

    public float Radius
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000001f9UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000001f9UL, value);
    }

    public float Density
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000001faUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000001faUL, value);
    }

    public float Friction
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000001fbUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000001fbUL, value);
    }

    public float Restitution
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000001fcUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000001fcUL, value);
    }
}

[RegisteredComponent(0x9f0000000000000fUL)]
public sealed partial class DistanceJoint2D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0000000000000fUL;

    internal DistanceJoint2D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000258UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000258UL, value);
    }

    public Vector2 Anchor
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x000000000000025aUL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x000000000000025aUL, value);
    }

    public Vector2 ConnectedAnchor
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x000000000000025bUL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x000000000000025bUL, value);
    }

    public float Distance
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000025cUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000025cUL, value);
    }

    public float Frequency
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000025dUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000025dUL, value);
    }

    public float Damping
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000025eUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000025eUL, value);
    }

    public bool CollideConnected
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x000000000000025fUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x000000000000025fUL, value);
    }
}

[RegisteredComponent(0x9f00000000000016UL)]
public sealed partial class MeshRenderer : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000016UL;

    internal MeshRenderer(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000640UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000640UL, value);
    }

    public Color Color
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x0000000000000641UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x0000000000000641UL, value);
    }

    public AssetRef<MeshAsset> Mesh
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x0000000000000642UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x0000000000000642UL, value.Handle);
    }

    public int Primitive
    {
        get => RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x0000000000000643UL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x0000000000000643UL, value);
    }

    public AssetRef<Texture2DAsset> Albedo
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x0000000000000644UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x0000000000000644UL, value.Handle);
    }

    public bool UseTexture
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000645UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000645UL, value);
    }

    public float Metallic
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000646UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000646UL, value);
    }

    public float Roughness
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000647UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000647UL, value);
    }

    public float AmbientOcclusion
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000648UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000648UL, value);
    }

    public Color Emission
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x0000000000000649UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x0000000000000649UL, value);
    }

    public float EmissionIntensity
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000064aUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000064aUL, value);
    }

    public bool CastShadows
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x000000000000064bUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x000000000000064bUL, value);
    }

    public bool ReceiveShadows
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x000000000000064cUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x000000000000064cUL, value);
    }
}

[RegisteredComponent(0x9f00000000000017UL)]
public sealed partial class Light3D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000017UL;

    internal Light3D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000006a4UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000006a4UL, value);
    }

    public int Type
    {
        get => RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x00000000000006a5UL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x00000000000006a5UL, value);
    }

    public Color Color
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x00000000000006a6UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x00000000000006a6UL, value);
    }

    public float Intensity
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006a7UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006a7UL, value);
    }

    public float Range
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006a8UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006a8UL, value);
    }

    public float InnerAngle
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006a9UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006a9UL, value);
    }

    public float OuterAngle
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006aaUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006aaUL, value);
    }

    public bool CastShadows
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x00000000000006abUL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x00000000000006abUL, value);
    }

    public float ShadowBias
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006acUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006acUL, value);
    }

    public float ShadowExtent
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x00000000000006adUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x00000000000006adUL, value);
    }
}

[RegisteredComponent(0x9f00000000000018UL)]
public sealed partial class Environment3D : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f00000000000018UL;

    internal Environment3D(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000708UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000708UL, value);
    }

    public bool ShowSky
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x0000000000000709UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x0000000000000709UL, value);
    }

    public AssetRef<Texture2DAsset> Panorama
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x000000000000070aUL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x000000000000070aUL, value.Handle);
    }

    public Color SkyColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x000000000000070bUL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x000000000000070bUL, value);
    }

    public Color GroundColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x000000000000070cUL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x000000000000070cUL, value);
    }

    public float Intensity
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000070dUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000070dUL, value);
    }

    public float AmbientIntensity
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000070eUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000070eUL, value);
    }

    public float Rotation
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x000000000000070fUL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x000000000000070fUL, value);
    }

    public float Exposure
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x0000000000000710UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x0000000000000710UL, value);
    }
}

[RegisteredComponent(0x9f01000000000001UL)]
public sealed partial class TextRenderer : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f01000000000001UL;

    internal TextRenderer(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01100000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01100000000001UL, value);
    }

    public AssetRef<FontAsset> Font
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x9f01100000000002UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x9f01100000000002UL, value.Handle);
    }

    public string Text
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01100000000003UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01100000000003UL, value);
    }

    public float FontSize
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01100000000004UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01100000000004UL, value);
    }

    public Color Color
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f01100000000005UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f01100000000005UL, value);
    }

    public TextAlignment Alignment
    {
        get => (TextAlignment)RegisteredComponentProperties.GetInt32(Entity, RegisteredTypeId, 0x9f01100000000006UL);
        set => RegisteredComponentProperties.SetInt32(Entity, RegisteredTypeId,
            0x9f01100000000006UL, (int)value);
    }

    public float MaxWidth
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01100000000007UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01100000000007UL, value);
    }

    public float LineSpacing
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01100000000008UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01100000000008UL, value);
    }

    public AssetRef<FontAsset> FallbackFont
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x9f01100000000009UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x9f01100000000009UL, value.Handle);
    }

    public AssetRef<FontAsset> EmojiFont
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x9f0110000000000aUL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x9f0110000000000aUL, value.Handle);
    }
}

[RegisteredComponent(0x9f01000000000009UL)]
public sealed partial class UISlider : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f01000000000009UL;

    internal UISlider(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01900000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01900000000001UL, value);
    }

    public bool Interactable
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01900000000002UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01900000000002UL, value);
    }

    public float Minimum
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01900000000003UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01900000000003UL, value);
    }

    public float Maximum
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01900000000004UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01900000000004UL, value);
    }

    public float Value
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01900000000005UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01900000000005UL, value);
    }

    public float Step
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01900000000006UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01900000000006UL, value);
    }

    public bool WholeNumbers
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01900000000007UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01900000000007UL, value);
    }

    public bool Vertical
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01900000000008UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01900000000008UL, value);
    }

    public Color TrackColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f01900000000009UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f01900000000009UL, value);
    }

    public Color FillColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f0190000000000aUL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f0190000000000aUL, value);
    }
}

[RegisteredComponent(0x9f0100000000000aUL)]
public sealed partial class UIScrollView : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0100000000000aUL;

    internal UIScrollView(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01a00000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01a00000000001UL, value);
    }

    public bool Horizontal
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01a00000000002UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01a00000000002UL, value);
    }

    public bool Vertical
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01a00000000003UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01a00000000003UL, value);
    }

    public Vector2 ContentSize
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x9f01a00000000004UL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x9f01a00000000004UL, value);
    }

    public Vector2 Offset
    {
        get => RegisteredComponentProperties.GetVector2(Entity, RegisteredTypeId, 0x9f01a00000000005UL);
        set => RegisteredComponentProperties.SetVector2(Entity, RegisteredTypeId,
            0x9f01a00000000005UL, value);
    }

    public float ScrollSpeed
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01a00000000006UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01a00000000006UL, value);
    }
}

[RegisteredComponent(0x9f0100000000000bUL)]
public sealed partial class UIInputField : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0100000000000bUL;

    internal UIInputField(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01b00000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01b00000000001UL, value);
    }

    public bool Interactable
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01b00000000002UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01b00000000002UL, value);
    }

    public string Text
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01b00000000003UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01b00000000003UL, value);
    }

    public string Placeholder
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01b00000000004UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01b00000000004UL, value);
    }

    public uint CharacterLimit
    {
        get => RegisteredComponentProperties.GetUInt32(Entity, RegisteredTypeId, 0x9f01b00000000005UL);
        set => RegisteredComponentProperties.SetUInt32(Entity, RegisteredTypeId,
            0x9f01b00000000005UL, value);
    }

    public bool Password
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01b00000000006UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01b00000000006UL, value);
    }

    public bool ReadOnly
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01b00000000007UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01b00000000007UL, value);
    }
}

[RegisteredComponent(0x9f0100000000000cUL)]
public sealed partial class UITheme : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0100000000000cUL;

    internal UITheme(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01c00000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01c00000000001UL, value);
    }

    public Color TextColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f01c00000000002UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f01c00000000002UL, value);
    }

    public Color ImageColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f01c00000000003UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f01c00000000003UL, value);
    }

    public Color AccentColor
    {
        get => RegisteredComponentProperties.GetColor(Entity, RegisteredTypeId, 0x9f01c00000000004UL);
        set => RegisteredComponentProperties.SetColor(Entity, RegisteredTypeId,
            0x9f01c00000000004UL, value);
    }

    public AssetRef<FontAsset> Font
    {
        get => new(RegisteredComponentProperties.GetUInt64(Entity, RegisteredTypeId, 0x9f01c00000000005UL));
        set => RegisteredComponentProperties.SetUInt64(Entity, RegisteredTypeId,
            0x9f01c00000000005UL, value.Handle);
    }

    public float FontScale
    {
        get => RegisteredComponentProperties.GetFloat(Entity, RegisteredTypeId, 0x9f01c00000000006UL);
        set => RegisteredComponentProperties.SetFloat(Entity, RegisteredTypeId,
            0x9f01c00000000006UL, value);
    }
}

[RegisteredComponent(0x9f0100000000000dUL)]
public sealed partial class UILocalization : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0100000000000dUL;

    internal UILocalization(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01d00000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01d00000000001UL, value);
    }

    public string Locale
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01d00000000002UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01d00000000002UL, value);
    }

    public string FallbackLocale
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01d00000000003UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01d00000000003UL, value);
    }

    public string Table
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01d00000000004UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01d00000000004UL, value);
    }
}

[RegisteredComponent(0x9f0100000000000eUL)]
public sealed partial class UILocalizedText : IEntityComponent
{
    public const ulong RegisteredTypeId = 0x9f0100000000000eUL;

    internal UILocalizedText(Entity entity) => Entity = entity;
    public Entity Entity { get; }

    public bool Enabled
    {
        get => RegisteredComponentProperties.GetBool(Entity, RegisteredTypeId, 0x9f01e00000000001UL);
        set => RegisteredComponentProperties.SetBool(Entity, RegisteredTypeId,
            0x9f01e00000000001UL, value);
    }

    public string Key
    {
        get => RegisteredComponentProperties.GetString(Entity, RegisteredTypeId, 0x9f01e00000000002UL);
        set => RegisteredComponentProperties.SetString(Entity, RegisteredTypeId,
            0x9f01e00000000002UL, value);
    }
}
