<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <RootNamespace>GameB</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../TomCat.Managed/TomCat.Managed.csproj" />
    <ProjectReference Include="../../TomCat.ScriptGenerator/TomCat.ScriptGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="ScriptAssets.json" />
  </ItemGroup>
</Project>
