<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TomCat.ScriptHost</AssemblyName>
    <RootNamespace>TomCat.ScriptHost</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TomCat.Managed/TomCat.Managed.csproj" />
  </ItemGroup>
</Project>
